[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "src"
version = "0.0.1"
authors = [{name = "Yifei Wang", email = "ywang13@renci.org"}]
description = "Heuristic and Optimal Algorithms for CSP and TE Computation"
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
Home = "https://github.com/atlanticwave-sdx/pce"
Issues = "https://github.com/atlanticwave-sdx/pce/issues"

[options.packages.find]
where = "src"
