[build-system]
requires = [
    "setuptools >= 45",
    "setuptools-scm >= 6.2"
]
build-backend = "setuptools.build_meta"

[project]
name = "LoadBalancing"
dynamic = [ "version" ]
authors = [{name = "Yifei Wang", email = "ywang13@renci.org"}]
description = "Heuristic and Optimal Algorithms for CSP and TE Computation"
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "matplotlib >= 3.4.3",
    "networkx >= 2.6.3",
    "numpy >= 1.20.3",
    "ortools >= 9.2.9972",
]

[project.urls]
Home = "https://github.com/atlanticwave-sdx/pce"
Issues = "https://github.com/atlanticwave-sdx/pce/issues"

[project.optional-dependencies]
test = [
    "pytest >= 7.1.2",
    "pytest-cov >= 3.0.0"
]

[options.packages.find]
where = "src"

[tool.pytest.ini_options]
addopts = "--cov --cov-report html --cov-report term-missing"
testpaths = [
    "tests"
]

[tool.setuptools_scm]
