[build-system]
requires = [
    "setuptools >= 44",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
src_paths = ["src", "tests", "setup.py"]

[tool.isort]
profile = "black"
src_paths = ["src", "tests", "setup.py"]
