# Run some code checks with GitHub Actions.

name: Code checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:

      - name: Check out sources
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'  # cache pip dependencies
          cache-dependency-path: pyproject.toml

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[lint]

      - name: Run "black --check"
        run: |
          python -m black --check $(git ls-files "*.py")

      - name: Run "isort --check"
        run: |
          python -m isort --check $(git ls-files "*.py")
