# Install Python dependencies, run tests and lint.
#
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  test:

    runs-on:
      - ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # See https://github.com/marketplace/actions/setup-python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'  # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov wheel
          if [ -f requirements.txt ]; then pip install --prefer-binary -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names.
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --statistics

      - name: Run tests
        run: |
          # Install package so that tests can be run.  Note that
          # editable mode install is important here -- it helps
          # coveralls.io to match coverage and sources correctly.
          pip install --editable .
          # Run tests and collect coverage data.
          python -m pytest
          # Convert coverage data to LCOV
          python -m coverage lcov

      # See https://github.com/marketplace/actions/coveralls-github-action
      - name: Send coverage data to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}         
          path-to-lcov: coverage.lcov
          flag-name: run-${{ matrix.python-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true          
